name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Install xcbeautify
        run: brew install xcbeautify

      - name: Test
        run: swift test | xcbeautify
