name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test