name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Install `xcbeautify`
        run:
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install xcbeautify

      - name: Build
        run: swift build

      - name: Test
        run: set -o pipefail && swift test | xcbeautify --is-ci
